### PR TITLE
inline datum

### PR DESCRIPTION
**Pull request by waalge**
https://github.com/orcfax/glossary/issues/7

### CODE REVIEW

**Review by Christian-MK — COMMENTED** [review]
Proposed edit
"A QoL improvement brought in with [CIP-32](https://cips.cardano.org/cip/CIP-32) and
      [CIP-31](https://cips.cardano.org/cip/CIP-31). Together, these allow reference inputs,
      which make it easier to use on-chain data in a plutus script."

**Comment by waalge** [comment]
@Christian-MK Your suggestion is incorrect. 

Inline datum is exclusively cip-32. Its a relatively subtle change to the scope of plutus scripts. The change did not really introduce any new functionality. It just augmented things previously achievable.

cip-31 is exclusively reference inputs. This really was a new feature.

**Comment by Christian-MK** [comment]
> @Christian-MK Your suggestion is incorrect.
> 
> Inline datum is exclusively cip-32. Its a relatively subtle change to the scope of plutus scripts. The change did not really introduce any new functionality. It just augmented things previously achievable.
> 
> cip-31 is exclusively reference inputs. This really was a new feature.

your proposal was:
```
A QoL improvement brought in with [CIP-32](https://cips.cardano.org/cip/CIP-32).
      Together with [CIP-31](https://cips.cardano.org/cip/CIP-31), allowing for reference inputs,
      it has made it easier to use on-chain data in a plutus script.
```
My edit was in response to "Together with", which is misleading then given your feedback.

**Comment by waalge** [comment]
> A QoL improvement brought in with [CIP-32](https://cips.cardano.org/cip/CIP-32) and
[CIP-31](https://cips.cardano.org/cip/CIP-31).

Suggests both CIPs relate to inline datum. They do not. Only one does.

>  Together, these allow reference inputs,
which make it easier to use on-chain data in a plutus script.

Suggests both CIPs relate to reference inputs. They do not. Only one does.

**Comment by Christian-MK** [comment]
> > A QoL improvement brought in with [CIP-32](https://cips.cardano.org/cip/CIP-32) and
> > [CIP-31](https://cips.cardano.org/cip/CIP-31).
> 
> Suggests both CIPs relate to inline datum. They do not. Only one does.
> 
> > Together, these allow reference inputs,
> > which make it easier to use on-chain data in a plutus script.
> 
> Suggests both CIPs relate to reference inputs. They do not. Only one does.

I'm not arguing with you, you know better than me in this area; I'm simply saying that your proposed definition was not sufficiently clear for me as a layperson. Is there a way to rework or add to your proposal which more clearly states what an inline datum is? Saying that it's a quality of life improvement doesn't tell me anything.

This glossary is meant, at least in part, to keep me from using terms incorrectly; your definition as it stands doesn't help me keep from being poked at by you.

**Comment by waalge** [comment]
Inline datum is a relatively subtle change to the internals of the cardano ledger that meant a plutus script could skip a step of checking that a piece of data correctly hashs to the target value, and simplifies txs that would have to also supply the aforementioned piece of data

To actually understand what inline datum really means, you'd have to read CIP32.

I don't what value a definition can add except to link to external source.

**Review by Christian-MK — DISMISSED** [review]
Lets get this added!

**Review by Christian-MK — DISMISSED** [review]

**Review by Christian-MK — APPROVED** [review]

**Pull request merged**
